import img from "../../../img/product/imgProduct.jpg";
const Products = [
  {
    id: 1,
    Name: "Product-001",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
  {
    id: 2,
    Name: "Product-002",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
  {
    id: 3,
    Name: "Product-003",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
  {
    id: 4,
    Name: "Product-004",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
  {
    id: 5,
    Name: "Product-005",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
  {
    id: 6,
    Name: "Product-006",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
  {
    id: 7,
    Name: "Product-007",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
  {
    id: 1,
    Name: "Product-001",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
  {
    id: 2,
    Name: "Product-002",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
  {
    id: 3,
    Name: "Product-003",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
  {
    id: 4,
    Name: "Product-004",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
  {
    id: 5,
    Name: "Product-005",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
  {
    id: 6,
    Name: "Product-006",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
  {
    id: 7,
    Name: "Product-007",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
  {
    id: 1,
    Name: "Product-001",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
  {
    id: 2,
    Name: "Product-002",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
  {
    id: 3,
    Name: "Product-003",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
  {
    id: 4,
    Name: "Product-004",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
  {
    id: 5,
    Name: "Product-005",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
  {
    id: 6,
    Name: "Product-006",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
  {
    id: 7,
    Name: "Product-007",
    Price: 10000,
    Discount: 0.1,
    IF: "Máy xịn",
    img: img,
  },
];
export { Products };
