import avt from "../../../img/avt/avt.jpg";
const users = [
  {
    id: 1,
    userName: "username01",
    avt: avt,
    Name: "NVA",
    Adress: "Quảng Nam",
    SDT: "012345678",
    Content: ["a", "b", "c", "shop", "key", "1", "2", "3", ".."],
    lastContent: "..",
  },
  {
    id: 2,
    userName: "username02",
    avt: avt,
    Name: "NVB",
    Adress: "HCM",
    SDT: "00000000",
    Content: ["a", "a", "a", "Hello"],
    lastContent: "Hello",
  },
  {
    id: 3,
    userName: "username01",
    avt: avt,
    Name: "NVA",
    Adress: "Quảng Nam",
    SDT: "012345678",
  },
  {
    id: 4,
    userName: "username02",
    avt: avt,
    Name: "NVB",
    Adress: "HCM",
    SDT: "00000000",
  },
  {
    id: 5,
    userName: "username01",
    avt: avt,
    Name: "NVA",
    Adress: "Quảng Nam",
    SDT: "012345678",
  },
  {
    id: 6,
    userName: "username02",
    avt: avt,
    Name: "NVB",
    Adress: "HCM",
    SDT: "00000000",
  },
  {
    id: 7,
    userName: "username01",
    avt: avt,
    Name: "NVA",
    Adress: "Quảng Nam",
    SDT: "012345678",
  },
  {
    id: 8,
    userName: "username02",
    avt: avt,
    Name: "NVB",
    Adress: "HCM",
    SDT: "00000000",
  },
  {
    id: 9,
    userName: "username01",
    avt: avt,
    Name: "NVA",
    Adress: "Quảng Nam",
    SDT: "012345678",
  },
  {
    id: 10,
    userName: "username02",
    avt: avt,
    Name: "NVB",
    Adress: "HCM",
    SDT: "00000000",
  },
  {
    id: 11,
    userName: "username01",
    avt: avt,
    Name: "NVA",
    Adress: "Quảng Nam",
    SDT: "012345678",
  },
  {
    id: 12,
    userName: "username02",
    avt: avt,
    Name: "NVB",
    Adress: "HCM",
    SDT: "00000000",
  },
  {
    id: 13,
    userName: "username01",
    avt: avt,
    Name: "NVA",
    Adress: "Quảng Nam",
    SDT: "012345678",
  },
  {
    id: 14,
    userName: "username02",
    avt: avt,
    Name: "NVB",
    Adress: "HCM",
    SDT: "00000000",
  },
  {
    id: 15,
    userName: "username01",
    avt: avt,
    Name: "NVA",
    Adress: "Quảng Nam",
    SDT: "012345678",
  },
  {
    id: 16,
    userName: "username02",
    avt: avt,
    Name: "NVB",
    Adress: "HCM",
    SDT: "00000000",
  },
  {
    id: 17,
    userName: "username01",
    avt: avt,
    Name: "NVA",
    Adress: "Quảng Nam",
    SDT: "012345678",
  },
  {
    id: 18,
    userName: "username02",
    avt: avt,
    Name: "NVB",
    Adress: "HCM",
    SDT: "00000000",
  },
  {
    id: 19,
    userName: "username01",
    avt: avt,
    Name: "NVA",
    Adress: "Quảng Nam",
    SDT: "012345678",
  },
  {
    id: 20,
    userName: "username02",
    avt: avt,
    Name: "NVB",
    Adress: "HCM",
    SDT: "00000000",
  },
  {
    id: 21,
    userName: "username01",
    avt: avt,
    Name: "NVA",
    Adress: "Quảng Nam",
    SDT: "012345678",
  },
  {
    id: 22,
    userName: "username02",
    avt: avt,
    Name: "NVB",
    Adress: "HCM",
    SDT: "00000000",
  },
  {
    id: 23,
    userName: "username01",
    avt: avt,
    Name: "NVA",
    Adress: "Quảng Nam",
    SDT: "012345678",
  },
  {
    id: 24,
    userName: "username02",
    avt: avt,
    Name: "NVB",
    Adress: "HCM",
    SDT: "00000000",
  },
  {
    id: 25,
    userName: "username01",
    avt: avt,
    Name: "NVA",
    Adress: "Quảng Nam",
    SDT: "012345678",
  },
  {
    id: 26,
    userName: "username02",
    avt: avt,
    Name: "NVB",
    Adress: "HCM",
    SDT: "00000000",
  },
  {
    id: 27,
    userName: "username01",
    avt: avt,
    Name: "NVA",
    Adress: "Quảng Nam",
    SDT: "012345678",
  },
  {
    id: 28,
    userName: "username02",
    avt: avt,
    Name: "NVB",
    Adress: "HCM",
    SDT: "00000000",
  },
  {
    id: 29,
    userName: "username01",
    avt: avt,
    Name: "NVA",
    Adress: "Quảng Nam",
    SDT: "012345678",
  },
  {
    id: 30,
    userName: "username02",
    avt: avt,
    Name: "NVB",
    Adress: "HCM",
    SDT: "00000000",
  },
  {
    id: 31,
    userName: "username01",
    avt: avt,
    Name: "NVA",
    Adress: "Quảng Nam",
    SDT: "012345678",
  },
  {
    id: 32,
    userName: "username02",
    avt: avt,
    Name: "NVB",
    Adress: "HCM",
    SDT: "00000000",
  },
  {
    id: 33,
    userName: "username01",
    avt: avt,
    Name: "NVA",
    Adress: "Quảng Nam",
    SDT: "012345678",
  },
  {
    id: 34,
    userName: "username02",
    avt: avt,
    Name: "NVB",
    Adress: "HCM",
    SDT: "00000000",
  },
  {
    id: 35,
    userName: "username01",
    avt: avt,
    Name: "NVA",
    Adress: "Quảng Nam",
    SDT: "012345678",
  },
  {
    id: 36,
    userName: "username02",
    avt: avt,
    Name: "NVB",
    Adress: "HCM",
    SDT: "00000000",
  },
  {
    id: 37,
    userName: "username01",
    avt: avt,
    Name: "NVA",
    Adress: "Quảng Nam",
    SDT: "012345678",
  },
  {
    id: 38,
    userName: "username02",
    avt: avt,
    Name: "NVB",
    Adress: "HCM",
    SDT: "00000000",
  },
  {
    id: 39,
    userName: "username01",
    avt: avt,
    Name: "NVA",
    Adress: "Quảng Nam",
    SDT: "012345678",
  },
  {
    id: 40,
    userName: "username02",
    avt: avt,
    Name: "NVB",
    Adress: "HCM",
    SDT: "00000000",
  },
];
export { users };
